name: nlbProtect
version: 1.1
main: ru.naulbimix.rupozor.Main
authors: [NaulbiMIX, Miku]
description: 'Просто, прикольный плагин написанный специально для участников группы vk.com/rupozor'
website: vk.com/evildonat